import { notFound } from "next/navigation";
import Link from "next/link";
import { Container } from "react-ui-vegetas-wife";
import { getBlogRepository } from "@/lib/blog/repository";
import { isAuthenticated } from "@/lib/auth";
import { getSocialRepository } from "@/lib/social/repository";
import { Button, Notification } from "react-ui-vegetas-wife";
import { publishToLinkedIn } from "../actions";
export const dynamic="force-dynamic";
export default async function PostPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{linkedin?:string}>}){const {slug}=await params;const post=await getBlogRepository().findBySlug(slug);if(!post)notFound();const [administrator, query] = await Promise.all([isAuthenticated(),searchParams]);const publication=administrator?await getSocialRepository().getPublication(post.id,"linkedin"):null;return <><section className="page-hero"><Container><div className="article-shell"><p className="eyebrow">Blog / {new Date(post.createdAt).toLocaleDateString("es-CO")}</p><h1 className="display-title gradient-text" style={{fontSize:"clamp(2.7rem,7vw,5.4rem)"}}>{post.title}</h1><p>{post.excerpt}</p></div></Container></section><section className="section-pad"><Container><article className="article-shell article-body"><div dangerouslySetInnerHTML={{__html:post.content}}/>{administrator&&<aside className="social-publish-panel glass">{query.linkedin==="published"&&<Notification color="success">Entrada publicada en LinkedIn.</Notification>}{query.linkedin==="error"&&<Notification color="danger">No se pudo publicar en LinkedIn. Revisa la conexión o vuelve a intentarlo.</Notification>}<strong>Distribución</strong><p className="muted">{publication?.status==="published"?"Esta entrada ya fue publicada en LinkedIn.":"Crea una publicación nativa de texto en LinkedIn con el título, resumen y contenido de esta entrada."}</p><form action={publishToLinkedIn}><input type="hidden" name="postId" value={post.id}/><Button color="primary" type="submit">{publication?.status==="published"?"Publicar otra vez en LinkedIn":"Publicar en LinkedIn"}</Button></form><Link href="/blog/admin/social/linkedin">Gestionar conexión</Link></aside>}<hr/><Link href="/blog">← Volver al blog</Link></article></Container></section></>}
